package engine

import (
	"context"
	"fmt"

	policieskyvernoio "github.com/kyverno/api/api/policies.kyverno.io"
	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/engine"
	ivpolautogen "github.com/kyverno/kyverno/pkg/cel/policies/ivpol/autogen"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/util/workqueue"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

type Provider = engine.Provider[Policy]

type ProviderFunc func(context.Context) ([]Policy, error)

func (f ProviderFunc) Fetch(ctx context.Context) ([]Policy, error) {
	return f(ctx)
}

func NewProvider(policies []policiesv1beta1.ImageValidatingPolicyLike, exceptions []*policiesv1beta1.PolicyException) (ProviderFunc, error) {
	compiled := make([]Policy, 0, len(policies))
	for _, policy := range policies {
		p := policy
		var matchedExceptions []*policiesv1beta1.PolicyException
		for _, polex := range exceptions {
			for _, ref := range polex.Spec.PolicyRefs {
				if ref.Name == p.GetName() && ref.Kind == p.GetKind() {
					matchedExceptions = append(matchedExceptions, polex)
				}
			}
		}
		actions := sets.New(p.GetSpec().ValidationActions()...)
		compiled = append(compiled, Policy{
			Actions:    actions,
			Policy:     p,
			Exceptions: matchedExceptions,
		})
		autogeneratedIvPols, err := ivpolautogen.Autogen(p)
		if err != nil {
			return nil, err
		}
		for _, ap := range autogeneratedIvPols {
			autogenPolicy := p.DeepCopyObject().(policiesv1beta1.ImageValidatingPolicyLike)
			*autogenPolicy.GetSpec() = *ap.Spec
			compiled = append(compiled, Policy{
				Actions: actions,
				Policy:  autogenPolicy,
			})
		}
	}
	provider := func(context.Context) ([]Policy, error) {
		return compiled, nil
	}
	return provider, nil
}

// policyExceptionRequestKey builds the reconcile key for the policy a PolicyException
// refers to. NamespacedImageValidatingPolicy is namespace-scoped, so the request must
// carry the exception's own namespace, otherwise Reconcile treats it as a cluster-scoped
// ImageValidatingPolicy lookup and the namespaced policy is never re-evaluated for the
// exception change.
func policyExceptionRequestKey(ref policiesv1beta1.PolicyRef, polexNamespace string) client.ObjectKey {
	key := client.ObjectKey{Name: ref.Name}
	if ref.Kind == policieskyvernoio.NamespacedImageValidatingPolicyKind {
		key.Namespace = polexNamespace
	}
	return key
}

func NewKubeProvider(
	mgr ctrl.Manager,
	polexLister engine.PolicyExceptionLister,
	polexEnabled bool,
) (Provider, error) {
	reconciler := newReconciler(mgr.GetClient(), polexLister, polexEnabled)
	ivpolBuilder := ctrl.NewControllerManagedBy(mgr).
		For(&policiesv1beta1.ImageValidatingPolicy{})

	nivpolBuilder := ctrl.NewControllerManagedBy(mgr).
		For(&policiesv1beta1.NamespacedImageValidatingPolicy{})

	if polexEnabled {
		exceptionHandlerFuncs := &handler.Funcs{
			CreateFunc: func(
				ctx context.Context,
				tce event.TypedCreateEvent[client.Object],
				trli workqueue.TypedRateLimitingInterface[reconcile.Request],
			) {
				polex := tce.Object.(*policiesv1beta1.PolicyException)
				for _, ref := range polex.Spec.PolicyRefs {
					trli.Add(reconcile.Request{NamespacedName: policyExceptionRequestKey(ref, polex.GetNamespace())})
				}
			},
			UpdateFunc: func(
				ctx context.Context,
				tue event.TypedUpdateEvent[client.Object],
				trli workqueue.TypedRateLimitingInterface[reconcile.Request],
			) {
				polex := tue.ObjectNew.(*policiesv1beta1.PolicyException)
				for _, ref := range polex.Spec.PolicyRefs {
					trli.Add(reconcile.Request{NamespacedName: policyExceptionRequestKey(ref, polex.GetNamespace())})
				}
			},
			DeleteFunc: func(
				ctx context.Context,
				tde event.TypedDeleteEvent[client.Object],
				trli workqueue.TypedRateLimitingInterface[reconcile.Request],
			) {
				polex := tde.Object.(*policiesv1beta1.PolicyException)
				for _, ref := range polex.Spec.PolicyRefs {
					trli.Add(reconcile.Request{NamespacedName: policyExceptionRequestKey(ref, polex.GetNamespace())})
				}
			},
		}
		ivpolBuilder = ivpolBuilder.Watches(&policiesv1beta1.PolicyException{}, exceptionHandlerFuncs)
		nivpolBuilder = nivpolBuilder.Watches(&policiesv1beta1.PolicyException{}, exceptionHandlerFuncs)
	}

	if err := ivpolBuilder.Complete(reconciler); err != nil {
		return nil, fmt.Errorf("failed to construct imagevalidatingpolicy manager: %w", err)
	}
	if err := nivpolBuilder.Complete(reconciler); err != nil {
		return nil, fmt.Errorf("failed to construct namespacedimagevalidatingpolicy manager: %w", err)
	}
	return reconciler, nil
}
